CREATE DATABASE BD_JOYERIA;
USE BD_JOYERIA;
CREATE TABLE CLIENTES (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    TELEFONO VARCHAR(15),
    DIRECCION VARCHAR(255)
);
